name: 'demo_project'
version: '1.0'
config-version: 2

profile: 'default'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

model-paths: ["models"]

models:
  demo_project:
    +materialized: view
